# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\smartSTitcher\3.18\arrangement_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 330)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.typelabel = QtWidgets.QLabel(Dialog)
        self.typelabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.typelabel.setObjectName("typelabel")
        self.horizontalLayout.addWidget(self.typelabel)
        self.TypeBox = QtWidgets.QComboBox(Dialog)
        self.TypeBox.setObjectName("TypeBox")
        self.TypeBox.addItem("")
        self.TypeBox.addItem("")
        self.TypeBox.addItem("")
        self.TypeBox.addItem("")
        self.TypeBox.addItem("")
        self.horizontalLayout.addWidget(self.TypeBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.orderlabel = QtWidgets.QLabel(Dialog)
        self.orderlabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.orderlabel.setObjectName("orderlabel")
        self.horizontalLayout_2.addWidget(self.orderlabel)
        self.orderBox = QtWidgets.QComboBox(Dialog)
        self.orderBox.setObjectName("orderBox")
        self.horizontalLayout_2.addWidget(self.orderBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.arrangementgraphicsView = QtWidgets.QGraphicsView(Dialog)
        self.arrangementgraphicsView.setObjectName("arrangementgraphicsView")
        self.horizontalLayout_3.addWidget(self.arrangementgraphicsView)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.typelabel.setText(_translate("Dialog", "type:"))
        self.TypeBox.setItemText(0, _translate("Dialog", "1.Grid: row-by-row"))
        self.TypeBox.setItemText(1, _translate("Dialog", "2.Grid: column-by-column"))
        self.TypeBox.setItemText(2, _translate("Dialog", "3.Grid: snake-by-row"))
        self.TypeBox.setItemText(3, _translate("Dialog", "4.Grid: snake-by-col"))
        self.TypeBox.setItemText(4, _translate("Dialog", "5.filened by filename"))
        self.orderlabel.setText(_translate("Dialog", "order:"))
