# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\lybstitch\smart_stitch\3.18\mip_preview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(762, 840)
        Form.setMinimumSize(QtCore.QSize(762, 840))
        Form.setMaximumSize(QtCore.QSize(762, 840))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MIPlabel = QtWidgets.QLabel(Form)
        self.MIPlabel.setMinimumSize(QtCore.QSize(600, 792))
        self.MIPlabel.setMaximumSize(QtCore.QSize(600, 792))
        self.MIPlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MIPlabel.setObjectName("MIPlabel")
        self.horizontalLayout.addWidget(self.MIPlabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.previewButton = QtWidgets.QPushButton(Form)
        self.previewButton.setMinimumSize(QtCore.QSize(75, 0))
        self.previewButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.previewButton.setObjectName("previewButton")
        self.verticalLayout.addWidget(self.previewButton)
        self.refreshpushButton = QtWidgets.QPushButton(Form)
        self.refreshpushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.refreshpushButton.setObjectName("refreshpushButton")
        self.verticalLayout.addWidget(self.refreshpushButton)
        self.classifypushButton = QtWidgets.QPushButton(Form)
        self.classifypushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.classifypushButton.setObjectName("classifypushButton")
        self.verticalLayout.addWidget(self.classifypushButton)
        self.erode_pushButton = QtWidgets.QPushButton(Form)
        self.erode_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.erode_pushButton.setObjectName("erode_pushButton")
        self.verticalLayout.addWidget(self.erode_pushButton)
        self.connect_pushButton = QtWidgets.QPushButton(Form)
        self.connect_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.connect_pushButton.setObjectName("connect_pushButton")
        self.verticalLayout.addWidget(self.connect_pushButton)
        self.submitpushButton = QtWidgets.QPushButton(Form)
        self.submitpushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.submitpushButton.setObjectName("submitpushButton")
        self.verticalLayout.addWidget(self.submitpushButton)
        self.poslable = QtWidgets.QLabel(Form)
        self.poslable.setMaximumSize(QtCore.QSize(16777215, 50))
        self.poslable.setObjectName("poslable")
        self.verticalLayout.addWidget(self.poslable)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.MIPlabel.setText(_translate("Form", "MIP preview"))
        self.previewButton.setText(_translate("Form", "create_preview"))
        self.refreshpushButton.setText(_translate("Form", "refresh"))
        self.classifypushButton.setText(_translate("Form", "classify"))
        self.erode_pushButton.setText(_translate("Form", "erode"))
        self.connect_pushButton.setText(_translate("Form", "connect"))
        self.submitpushButton.setText(_translate("Form", "submit"))
        self.poslable.setText(_translate("Form", "所选块："))
